// @ts-check
/**
 * Embed generator acceptance (blueprint 7.10, 12.3 lane L14): the generator writes the blueprint 1.5 snippet,
 * the "All Snippets" table equals the generator's output row by row, the live preview loads the chosen page, and a
 * snippet pasted into a host page (a stand-in for a Squarespace Code Block) frames the dashboard in embed mode
 * and sizes itself with the host helper.
 *
 * The page's Content-Security-Policy meta is generated by lane L15's check:csp, which derives `frame-src 'self'`
 * for this page only (Wave 2 finisher, at this lane's request) and `frame-src 'none'` everywhere else. The
 * preview tests run under the shipped policy and first assert that it is the one served.
 */
import { expect, test } from '@playwright/test';
import { AxeBuilder } from '@axe-core/playwright';

const BLUEPRINT_ALERTS = `<iframe data-cthd
  src="https://atniclimate.github.io/pnw-tribal-dashboard/alerts/?embed=1"
  title="Cascadia Tribal Hazard Dashboard: Active Alerts"
  style="width:100%;height:1200px;border:0;display:block;"
  loading="eager"
  referrerpolicy="strict-origin-when-cross-origin"></iframe>
<script src="https://atniclimate.github.io/pnw-tribal-dashboard/embed.js" defer></script>`;

/** @param {import('@playwright/test').Page} page */
async function withPreviewCsp(page) {
  // No rewriting: the shipped meta policy must already allow same-origin frames on this page.
  await page.route('**/embed/', async (route) => {
    const res = await route.fetch();
    const body = await res.text();
    expect(body).toContain("frame-src 'self'");
    await route.fulfill({ response: res, body });
  });
}

/** @param {import('@playwright/test').Page} page */
const snippet = (page) => page.locator('#embed-snippet').inputValue();

test('the generator opens on the whole Dashboard with the snippet ready to copy', async ({ page }) => {
  await page.goto('embed/');
  await expect(page.locator('#embed-snippet')).toHaveValue(/^<iframe data-cthd\n/);
  expect(await snippet(page)).toContain('src="https://atniclimate.github.io/pnw-tribal-dashboard/?embed=1"');
  expect(await snippet(page)).toContain('height:1500px;');
  await expect(page.locator('#embed-height')).toHaveValue('1500');
  await expect(page.getByRole('button', { name: 'Copy Snippet' })).toBeVisible();
});

test('choosing Alerts writes the blueprint 1.5 example exactly', async ({ page }) => {
  await page.goto('embed/');
  await page.locator('#embed-page').selectOption('alerts');
  expect(await snippet(page)).toBe(BLUEPRINT_ALERTS.replace('?embed=1"', '?embed=1"'));
  await expect(page.locator('#embed-height')).toHaveValue('1200');
});

test('a view, a height, no helper script, lazy loading, and location each change only their own part', async ({ page }) => {
  await page.goto('embed/');
  await page.locator('#embed-page').selectOption('contacts');
  await expect(page.locator('#embed-view')).toBeVisible();
  await page.locator('#embed-view').selectOption('near-me');
  let code = await snippet(page);
  expect(code).toContain('src="https://atniclimate.github.io/pnw-tribal-dashboard/contacts/?embed=1&amp;view=near-me"');
  expect(code).toContain('allow="geolocation"');
  await page.locator('#embed-height').fill('900');
  await page.locator('#embed-auto').uncheck();
  await page.locator('#embed-lazy').check();
  await page.locator('#embed-geo').uncheck();
  code = await snippet(page);
  expect(code).toBe(`<iframe data-cthd
  src="https://atniclimate.github.io/pnw-tribal-dashboard/contacts/?embed=1&amp;view=near-me"
  title="Cascadia Tribal Hazard Dashboard: Contacts, Near Me"
  style="width:100%;height:900px;border:0;display:block;"
  loading="lazy"
  referrerpolicy="strict-origin-when-cross-origin"></iframe>`);
});

test('the Dashboard header strip is /?embed=1&panel=banner at 96 px with no script line', async ({ page }) => {
  await page.goto('embed/');
  await page.locator('#embed-panel').selectOption('banner');
  const code = await snippet(page);
  expect(code).toContain('src="https://atniclimate.github.io/pnw-tribal-dashboard/?embed=1&amp;panel=banner"');
  expect(code).toContain('height:96px;');
  expect(code).not.toContain('<script');
  await expect(page.locator('#embed-notes')).toContainText('320 pixels');
});

test('fields that do not apply to a page are hidden, and their values never reach the snippet', async ({ page }) => {
  await page.goto('embed/');
  await page.locator('#embed-page').selectOption('news');
  await expect(page.locator('#embed-nation')).toBeHidden();
  await expect(page.locator('#embed-view')).toBeHidden();
  await expect(page.locator('#embed-panel')).toBeHidden();
  await page.locator('#embed-page').selectOption('alerts');
  await expect(page.locator('#embed-nation')).toBeVisible();
  await expect(page.locator('#embed-view')).toBeVisible();
  await page.locator('#embed-nation').fill('us-wa-lummi-nation');
  expect(await snippet(page)).toContain('?embed=1&amp;n=us-wa-lummi-nation"');
  await page.locator('#embed-page').selectOption('news');
  expect(await snippet(page)).not.toContain('n=');
});

test('a Nation chosen by full name from the list becomes its id; an unknown name is explained', async ({ page }) => {
  await page.goto('embed/');
  await page.locator('#embed-page').selectOption('alerts');
  await expect.poll(() => page.locator('#embed-nation-list option').count()).toBeGreaterThan(10);
  const name = await page.locator('#embed-nation-list option').first().getAttribute('value');
  expect(name).toBeTruthy();
  await page.locator('#embed-nation').fill(/** @type {string} */ (name));
  expect(await snippet(page)).toMatch(/\?embed=1&amp;n=(?:us-[a-z]{2}|ca-fn)-[a-z0-9-]+"/);
  await expect(page.locator('#embed-notes')).not.toContainText('not recognized');
  await page.locator('#embed-nation').fill('No Such Nation Anywhere');
  expect(await snippet(page)).not.toContain('n=');
  await expect(page.locator('#embed-notes')).toContainText('not recognized');
});

test('the All Snippets table has one row per page and view, and each row equals the generator\'s output', async ({ page }) => {
  await page.goto('embed/');
  const rows = page.locator('#embed-table tbody tr');
  const count = await rows.count();
  expect(count).toBe(28);
  const keys = await rows.evaluateAll((trs) => trs.map((t) => t.getAttribute('data-row') ?? ''));
  expect(new Set(keys).size).toBe(count);
  for (const key of keys) {
    const row = page.locator(`#embed-table tr[data-row="${key}"]`);
    const shown = (await row.locator('pre code').textContent()) ?? '';
    await row.locator('[data-use-row]').evaluate((b) => /** @type {HTMLElement} */ (b).click());
    expect(await snippet(page), key).toBe(shown);
  }
});

test('every row is a complete snippet with the iframe, a title, and (unless a strip) the helper script', async ({ page }) => {
  await page.goto('embed/');
  const codes = await page.locator('#embed-table pre code').allTextContents();
  expect(codes.length).toBe(28);
  for (const c of codes) {
    expect(c).toMatch(/^<iframe data-cthd\n {2}src="https:\/\/atniclimate\.github\.io\/pnw-tribal-dashboard\/[^"]*"\n {2}title="[^"]+"\n/);
    expect(c.endsWith('</iframe>') || c.endsWith('defer></script>')).toBe(true);
  }
  expect(codes.filter((c) => !c.includes('<script')).length).toBe(1);
});

test('Copy Snippet puts exactly the snippet on the clipboard and says so', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.goto('embed/');
  await page.locator('#embed-page').selectOption('forecasts');
  await page.locator('#embed-view').selectOption('radar');
  const want = await snippet(page);
  await page.getByRole('button', { name: 'Copy Snippet' }).click();
  // Windows clipboards hand text back with CRLF line ends; a paste into a Code Block treats both alike.
  expect((await page.evaluate(() => navigator.clipboard.readText())).replace(/\r\n/g, '\n')).toBe(want);
  await expect(page.locator('#embed-status')).toContainText('Snippet copied');
});

test('the live preview loads the chosen page in embed mode and follows the choices', async ({ page }) => {
  await withPreviewCsp(page);
  await page.goto('embed/');
  const preview = page.locator('#embed-preview');
  await expect(preview).toHaveAttribute('src', '../?embed=1');
  await expect(page.frameLocator('#embed-preview').locator('html')).toHaveAttribute('data-embed', '1');
  await page.locator('#embed-page').selectOption('archive-event');
  await expect(preview).toHaveAttribute('src', '../archive/2025-12-atmospheric-river/?embed=1');
  const frame = page.frameLocator('#embed-preview');
  await expect(frame.locator('.archive-banner')).toBeVisible();
  await page.locator('#embed-page').selectOption('news');
  await expect(preview).toHaveAttribute('src', '../news/?embed=1');
  await expect(frame.locator('h1')).toHaveText('News');
});

test('the preview sizes itself from the page\'s height messages when auto-height is on, and holds the fixed height when off', async ({ page }) => {
  await withPreviewCsp(page);
  await page.goto('embed/');
  await page.locator('#embed-page').selectOption('archive-event');
  await expect(page.frameLocator('#embed-preview').locator('.archive-entry').first()).toBeVisible();
  const frameHeight = () => page.locator('#embed-preview').evaluate((el) => Math.round(el.getBoundingClientRect().height));
  await expect.poll(async () => {
    const inner = await page.frameLocator('#embed-preview').locator('html').evaluate((el) => Math.ceil(el.getBoundingClientRect().height));
    return Math.abs((await frameHeight()) - inner) <= 2;
  }).toBe(true);
  await page.locator('#embed-auto').uncheck();
  await page.locator('#embed-height').fill('777');
  await expect.poll(frameHeight).toBe(777);
});

test.describe('pasted into a host page, the way a Squarespace Code Block holds it', () => {
  /**
   * A stand-in host (no real Squarespace): the snippet is placed inside ordinary host markup, the published
   * address is answered from this site's own files, and nothing else is faked.
   * @param {import('@playwright/test').Page} page
   * @param {string} code
   * @param {string} base the local site origin and path
   */
  async function hostPage(page, code, base) {
    await page.route('https://squarespace-host.test/**', (route) => route.fulfill({
      contentType: 'text/html',
      body: `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Host page</title></head><body style="margin:0"><main><h1>Host page</h1><div class="sqs-block-code">${code}</div></main></body></html>`,
    }));
    await page.route('https://atniclimate.github.io/pnw-tribal-dashboard/**', async (route) => {
      const u = new URL(route.request().url());
      const res = await route.fetch({ url: `${base}${u.pathname.replace('/pnw-tribal-dashboard/', '')}${u.search}` });
      await route.fulfill({ response: res });
    });
  }

  test('the framed page is in embed mode, keeps its notes, and the helper sets the frame height', async ({ page, baseURL }) => {
    const code = (await (async () => {
      await page.goto('embed/');
      await page.locator('#embed-page').selectOption('archive-event');
      return snippet(page);
    })());
    await hostPage(page, code, /** @type {string} */ (baseURL));
    await page.goto('https://squarespace-host.test/');
    const frame = page.frameLocator('iframe[data-cthd]');
    await expect(frame.locator('html')).toHaveAttribute('data-embed', '1');
    await expect(frame.locator('.archive-banner')).toBeVisible();
    await expect(frame.locator('.site-footer__sovereignty')).toBeVisible();
    await expect(frame.locator('[data-provenance]').first()).toBeVisible();
    const fixed = 1100;
    await expect.poll(async () => {
      const h = await page.locator('iframe[data-cthd]').evaluate((el) => Math.round(el.getBoundingClientRect().height));
      return h !== fixed;
    }).toBe(true);
    // The framed page keeps growing while its panels render, and the helper follows each height message, so the
    // frame converges on the framed document's height rather than matching the first message.
    const outer = () => page.locator('iframe[data-cthd]').evaluate((el) => Math.round(el.getBoundingClientRect().height));
    const inner = () => frame.locator('html').evaluate((el) => Math.ceil(el.getBoundingClientRect().height));
    await expect.poll(async () => Math.abs((await outer()) - (await inner())), { timeout: 10_000 }).toBeLessThanOrEqual(2);
    const h = await outer();
    expect(h).toBeGreaterThanOrEqual(320);
    expect(h).toBeLessThanOrEqual(6000);
  });

  test('without the script line the frame keeps the height written in the snippet', async ({ page, baseURL }) => {
    await page.goto('embed/');
    await page.locator('#embed-page').selectOption('archive-event');
    await page.locator('#embed-auto').uncheck();
    const code = await snippet(page);
    expect(code).not.toContain('<script');
    await hostPage(page, code, /** @type {string} */ (baseURL));
    await page.goto('https://squarespace-host.test/');
    await expect(page.frameLocator('iframe[data-cthd]').locator('.archive-entry').first()).toBeVisible();
    await page.waitForTimeout(600);
    expect(await page.locator('iframe[data-cthd]').evaluate((el) => Math.round(el.getBoundingClientRect().height))).toBe(1100);
  });

  test('links that leave the framed page open in a new tab, so the host page stays put', async ({ page, baseURL }) => {
    await page.goto('embed/');
    await page.locator('#embed-page').selectOption('archive-event');
    const code = await snippet(page);
    await hostPage(page, code, /** @type {string} */ (baseURL));
    await page.goto('https://squarespace-host.test/');
    const links = page.frameLocator('iframe[data-cthd]').locator('.archive-entry a');
    await expect(links.first()).toBeVisible();
    await links.first().focus();
    await links.first().hover();
    expect(await links.first().getAttribute('target')).toBe('_blank');
    expect(await links.first().getAttribute('rel')).toContain('noopener');
    await expect(page.frameLocator('iframe[data-cthd]').locator('a[data-embed-open]')).toHaveAttribute('target', '_blank');
  });
});

test('no serious or critical accessibility violation on the page, with the preview open', async ({ page }) => {
  await withPreviewCsp(page);
  await page.goto('embed/');
  await expect(page.frameLocator('#embed-preview').locator('html')).toHaveAttribute('data-embed', '1');
  const r = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'wcag22aa']).exclude('#embed-preview').analyze();
  const bad = r.violations.filter((v) => v.impact === 'serious' || v.impact === 'critical').map((v) => `${v.id}: ${v.nodes.map((n) => n.target.join(' ')).join(' | ')}`);
  expect(bad).toEqual([]);
});

test('no horizontal scroll at phone width, and the page is not itself embeddable chrome-less content', async ({ page }) => {
  await page.goto('embed/');
  await expect(page.locator('#embed-snippet')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1)).toBe(false);
  await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content', 'noindex');
});

test('every request goes to this site: the page and its preview contact no third party', async ({ page }) => {
  await withPreviewCsp(page);
  /** @type {string[]} */
  const urls = [];
  page.on('request', (r) => urls.push(r.url()));
  await page.goto('embed/');
  await expect(page.frameLocator('#embed-preview').locator('html')).toHaveAttribute('data-embed', '1');
  await page.waitForLoadState('networkidle');
  expect([...new Set(urls.map((u) => new URL(u).hostname))]).toEqual(['localhost']);
});
